"""Speech-to-Text inference wrapper and thread management."""

import os
from concurrent.futures import ThreadPoolExecutor
from typing import Any

from faster_whisper import WhisperModel
from loguru import logger

from aisrt.hardware import ModelConfig


class STTWorker:
    """Singleton wrapper for the WhisperModel and ThreadPoolExecutor.

    Ensures that only one model is loaded into VRAM/RAM and all inference
    requests are queued into a single thread to prevent GIL starvation
    in the main asyncio event loop.
    """

    _instance: "STTWorker | None" = None
    model: WhisperModel | None
    executor: ThreadPoolExecutor

    def __new__(cls, *args: Any, **kwargs: Any) -> "STTWorker":
        """Ensure singleton instance."""
        if not cls._instance:
            cls._instance = super().__new__(cls)
            cls._instance.model = None
            # Strict max_workers=1 to ensure GPU/CPU isn't thrashed
            cls._instance.executor = ThreadPoolExecutor(max_workers=1)
        return cls._instance

    def initialize(self, config: ModelConfig) -> None:
        """Initialize the WhisperModel with the routed configuration.

        Args:
            config: The ModelConfig generated by the HardwareProfiler.
        """
        if self.model is not None:
            return

        hf_token = os.environ.get("HF_TOKEN")
        if hf_token:
            logger.info("Authenticating with HuggingFace Hub to bypass rate limits...")
            try:
                from huggingface_hub import login
                login(token=hf_token)
            except Exception as e:
                logger.warning(f"HuggingFace login failed: {e}")

        logger.info(
            f"Initializing WhisperModel '{config.model_name}' "
            f"on {config.device} ({config.compute_type})..."
        )

        def _load_model() -> WhisperModel | Any:
            model = WhisperModel(
                model_size_or_path=config.model_name,
                device=config.device,
                compute_type=config.compute_type,
                cpu_threads=config.cpu_threads,
                num_workers=1,  # Keep inner workers to 1 since we'll process sequentially
            )

            if config.device == "cuda":
                try:
                    from faster_whisper import BatchedInferencePipeline

                    logger.info("CUDA detected. Loading BatchedInferencePipeline...")
                    return BatchedInferencePipeline(model=model)
                except ImportError:
                    logger.warning(
                        "BatchedInferencePipeline not found. Ensure faster_whisper >= 1.0."
                    )

            return model

        # Initialize asynchronously using the dedicated executor to not block main thread
        future = self.executor.submit(_load_model)
        self.model = future.result()
        logger.info("WhisperModel successfully loaded.")

    def close(self) -> None:
        """Shutdown the executor cleanly."""
        if self.executor:
            self.executor.shutdown(wait=True)
            self.model = None
            STTWorker._instance = None
